services:
  liquidsoap:  
    build:
      context: ./liquidsoap
    container_name: liquidsoap
    restart: always
    volumes:
      - ./music:/etc/music:rw
    environment:
      - PLAYLIST_URL=/etc/music
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-hackme}
      - ICECAST_MOUNT=/stream
      - ADMIN_BASE_URL=http://admin:5179
    user: "liquidsoap:3000"
    networks:
      - radionetwork

  icecast:
    build:
      context: ./icecast
    container_name: icecast
    restart: always
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-hackme}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD:-hackme}
    ports:
      - "8000:8000"
    networks:
      - radionetwork

  admin:
    build:
      context: ./admin
    volumes:
      - ./music:/etc/music:rw
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5179
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379,password=hackme
      - Storage__Provider=Local
      - Storage__LocalPath=/etc/music
    ports:
      - "5179:5179"
    group_add: 
      - "3000"
    user: "1654:3000"
    networks:
      - radionetwork

  player:
    build:
      context: ./player
    environment:
      - ASPNETCORE_URLS=http://0.0.0:5178
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379,password=hackme
      - Radio__StreamUrl=http://localhost:8000/stream
      - Radio__AdminApiBaseUrl=http://admin:5179
    ports:
      - "5178:5178"
    networks:
      - radionetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass hackme --appendonly yes
    restart: unless-stopped
    networks:
      - radionetwork


volumes:
  redis-data:
    driver: local

networks:
  radionetwork:
    driver: bridge