services:
  liquidsoap:  
    image: "savonet/liquidsoap:v2.4.x-latest"
    container_name: liquidsoap
    restart: always
    volumes:
      - ./liquidsoap/script.liq:/etc/liquidsoap/script.liq:ro
      - ./music:/etc/music:rw
    command: "/etc/liquidsoap/script.liq"
    user: "liquidsoap:3000"
    networks:
      - radionetwork

  icecast:
    image: "libretime/icecast:2.5.0"
    container_name: icecast
    restart: always
    volumes:
      - ./icecast/icecast.xml:/etc/icecast.xml
    ports:
      - "8000:8000"
    networks:
      - radionetwork

  admin:
    build:
      context: ./admin
    volumes:
      - ./music:/etc/music:rw
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5179
    ports:
      - "5179:5179"
    group_add: 
      - "3000"
    user: "1654:3000"
    networks:
      - radionetwork

  player:
    build:
      context: ./player
    environment:
      - ASPNETCORE_URLS=http://0.0.0:5178
    ports:
      - "5178:5178"
    networks:
      - radionetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass hackme --appendonly yes
    restart: unless-stopped
    networks:
      - radionetwork